config/routes.rb
Rails.application.routes.draw do
  ## we call the resources method and pass it a Symbol
  resources :topics do
    resources :posts, except: [:index]
  end

  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end
  ## we create routes for new and create actions
  resources :users, only: [:new, :create, :show]

  resources :sessions, only: [:new, :create, :destroy]

  ## we remove get "welcome/index" because we've declared the index view as the root view
  get 'about' => 'welcome#about'

  root 'welcome#index'

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :posts, dependent: :destroy
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  before_action :require_sign_in, except: [:index, :show]
  before_action :authorize_user, except: [:index, :show]

  def index
    @topics = Topic.all
  end

  def show
    @topic = Topic.find(params[:id])
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)

    if @topic.save
      redirect_to @topic, notice: "Topic was saved successfully."
    else
      flash.now[:alert] = "Error creating topic. Please try again."
      render :new
    end
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def update
    @topic = Topic.find(params[:id])

    @topic.assign_attributes(topic_params)

    if @topic.save
       flash[:notice] = "Topic was updated."
      redirect_to @topic
    else
      flash.now[:alert] = "Error saving topic. Please try again."
      render :edit
    end
  end

  def destroy
    @topic = Topic.find(params[:id])

    if @topic.destroy
      flash[:notice] = "\"#{@topic.name}\" was deleted successfully."
      redirect_to action: :index
    else
      flash.now[:alert] = "There was an error deleting the topic."
      render :show
    end
  end

  private

  def topic_params
    params.require(:topic).permit(:name, :description, :public)
  end

  def authorize_user
    unless current_user.admin?
      flash[:alert] = "You must be an admin to do that."
      redirect_to topics_path
    end
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
  def user_is_authorized_for_topics?
       current_user && current_user.admin?
  end
end

app/views/topics/edit.html.erb
<h1>Edit Topic</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for topics:</p>
    <ul>
      <li>Make sure the topic is appropriate.</li>
      <li>Never insult dogs.</li>
      <li>Smile when you type.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @topic do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', placeholder: "Enter topic name" %>
      </div>
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "Enter topic description" %>
      </div>
      <div class="form-group">
<!-- #11 we pass a block to f.label to generate the HTML for a checkbox -->
        <%= f.label :public, class: 'checkbox' do %>
          <%= f.check_box :public %> Public topic
        <% end %>
      </div>
      <%= f.submit "Save", class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/topics/index.html.erb
<h1>Topics</h1>

<div class="row">
  <div class="col-md-8">
<!-- #7 we loop over each topic in @topics -->
    <% @topics.each do |topic| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
<!-- #8 we create a link to the show view for each topic -->
            <%= link_to topic.name, topic %>
          </h4>
          <small>
            <%= topic.description %>
          </small>
        </div>
      </div>
    <% end %>
  </div>
  <% if user_is_authorized_for_topics? %>
    <div class="col-md-4">
  <!-- #9 we create a link to create a new topic -->
      <%= link_to "New Topic", new_topic_path, class: 'btn btn-success' %>
    </div>
  <% end %>
</div>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for topics:</p>
    <ul>
      <li>Make sure the topic is appropriate.</li>
      <li>Never insult dogs.</li>
      <li>Smile when you type.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @topic do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', placeholder: "Enter topic name" %>
      </div>
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "Enter topic description" %>
      </div>
      <div class="form-group">
        <%= f.label :public, class: 'checkbox' do %>
          <%= f.check_box :public %> Public topic
        <% end %>
      </div>
      <%= f.submit "Save", class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/topics/show.html.erb
<h1><%= @topic.name %></h1>

<% if user_is_authorized_for_topics? %>
  <%= link_to "Edit Topic", edit_topic_path, class: 'btn btn-success' %>
  <%= link_to "Delete Topic", @topic, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this topic?' } %>
<% end %>
<div class="row">
  <div class="col-md-8">
    <p class="lead"><%= @topic.description %></p>
<!-- #10 we iterate over the posts belonging to @topic, and display each post -->
    <% @topic.posts.each do |post| %>
      <div class="media">
        <%= render partial: 'votes/voter', locals: { post: post } %>
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to post.title, topic_post_path(@topic, post) %>
          </h4>
          <small>
             submitted <%= time_ago_in_words(post.created_at) %> ago by <%= post.user.name %> <br>
             <%= post.comments.count %> Comments
          </small>
        </div>
      </div>
    <% end %>
  </div>
<% if current_user %>
  <div class="col-md-4">
    <%= link_to "New Post", new_topic_post_path(@topic), class: 'btn btn-success' %>
  </div>
<% end %>
</div>