config/routes.rb
Rails.application.routes.draw do
  ## we call the resources method and pass it a Symbol
  resources :topics do
    resources :posts, except: [:index]
  end

  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end
  ## we create routes for new and create actions
  resources :users, only: [:new, :create, :show]

  resources :sessions, only: [:new, :create, :destroy]

  ## we remove get "welcome/index" because we've declared the index view as the root view
  get 'about' => 'welcome#about'

  root 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bloccit</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Bloccit", root_path %></li>
      <li><%= link_to "Topics", topics_path %></li>
      <li><%= link_to "About", about_path %></li>

      <div class="pull-right user-info">
        <% if current_user %>
        <%= image_tag current_user.avatar_url(48), class: "gravatar" %>
        <div class="pull-right">
          <%= link_to current_user.name, user_path(current_user) %> <br/> <%= link_to "Sign Out", session_path(current_user), method: :delete %>
        </div>
        <% else %>
             <%= link_to "Sign In", new_session_path %> or
             <%= link_to "Sign Up", new_user_path %>
           <% end %>
      </div>

    </ul>

    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>
  </div>

</body>
</html>